# Generated by Django 6.0.2 on 2026-03-24 18:37

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('front', models.CharField(max_length=50)),
                ('back', models.CharField(max_length=50)),
                ('examples', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hint', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='vocabulary.deck')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(default=1)),
                ('repetitions', models.IntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='vocabulary.card')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cards', models.IntegerField()),
                ('correct_answers', models.IntegerField(default=0)),
                ('incorrect_answers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabulary.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSessionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('answered', models.BooleanField(default=False)),
                ('rating', models.CharField(blank=True, choices=[('again', 'Again'), ('hard', 'Hard'), ('good', 'Good'), ('easy', 'Easy')], max_length=10, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.card')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_cards', to='vocabulary.reviewsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='deck',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='unique_deck_per_user'),
        ),
        migrations.AddConstraint(
            model_name='deck',
            constraint=models.UniqueConstraint(models.F('user'), models.F('slug'), name='unique_deck_slug_per_user'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(models.F('slug'), models.F('user'), name='unique_card_slug_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewsessioncard',
            unique_together={('session', 'card')},
        ),
    ]
