# Generated by Django 6.0 on 2026-05-04 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cardprogress',
            name='last_review',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardprogress',
            name='next_review',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
