# Generated by Django 6.0 on 2026-05-11 18:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cardprogress',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_progress', to='vocabulary.card'),
        ),
        migrations.AlterField(
            model_name='cardprogress',
            name='last_review',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardprogress',
            name='next_review',
            field=models.DateField(default=datetime.date(2026, 5, 11)),
        ),
    ]
