# Generated by Django 6.0 on 2026-05-13 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_card_created_at_alter_cardprogress_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprogress',
            name='next_review',
            field=models.DateField(default=datetime.date(2026, 5, 13)),
        ),
    ]
