# Generated by Django 6.0 on 2026-05-04 10:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_card_created_at_alter_cardprogress_last_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprogress',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_progress', to='vocabulary.card'),
        ),
        migrations.AlterField(
            model_name='cardprogress',
            name='next_review',
            field=models.DateField(default=datetime.date(2026, 5, 4)),
        ),
    ]
