# Generated by Django 6.0 on 2026-05-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_alter_cardprogress_card_and_more'),
        ('vocabulary', '0003_alter_cardprogress_next_review'),
    ]

    operations = [
    ]
