# Generated by Django 6.0 on 2026-05-19 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_merge_20260519_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprogress',
            name='next_review',
            field=models.DateField(default=datetime.date(2026, 5, 19)),
        ),
    ]
