# Generated by Django 6.0 on 2026-05-24 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0005_alter_cardprogress_next_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprogress',
            name='next_review',
            field=models.DateField(default=datetime.date(2026, 5, 24)),
        ),
    ]
