# Generated by Django 6.0.2 on 2026-02-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
