# Generated by Django 6.0 on 2026-05-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_telegramprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
