# Generated by Django 6.0 on 2026-05-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_telegramprofile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
