# Generated by Django 6.0 on 2026-05-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_delete_telegramprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstreak',
            name='is_active_today',
            field=models.BooleanField(default=False),
        ),
    ]
