# Generated by Django 6.0 on 2026-05-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userstreak_is_active_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstreak',
            name='current_streak',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userstreak',
            name='max_streak',
            field=models.IntegerField(default=1),
        ),
    ]
